/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FinanceImport } from './routes/finance'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const FinanceIndexLazyImport = createFileRoute('/finance/')()
const FinanceExpenseLazyImport = createFileRoute('/finance/expense')()

// Create/Update Routes

const FinanceRoute = FinanceImport.update({
  path: '/finance',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FinanceIndexLazyRoute = FinanceIndexLazyImport.update({
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any).lazy(() => import('./routes/finance.index.lazy').then((d) => d.Route))

const FinanceExpenseLazyRoute = FinanceExpenseLazyImport.update({
  path: '/expense',
  getParentRoute: () => FinanceRoute,
} as any).lazy(() =>
  import('./routes/finance.expense.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceImport
      parentRoute: typeof rootRoute
    }
    '/finance/expense': {
      id: '/finance/expense'
      path: '/expense'
      fullPath: '/finance/expense'
      preLoaderRoute: typeof FinanceExpenseLazyImport
      parentRoute: typeof FinanceImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexLazyImport
      parentRoute: typeof FinanceImport
    }
  }
}

// Create and export the route tree

interface FinanceRouteChildren {
  FinanceExpenseLazyRoute: typeof FinanceExpenseLazyRoute
  FinanceIndexLazyRoute: typeof FinanceIndexLazyRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceExpenseLazyRoute: FinanceExpenseLazyRoute,
  FinanceIndexLazyRoute: FinanceIndexLazyRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/finance': typeof FinanceRouteWithChildren
  '/finance/expense': typeof FinanceExpenseLazyRoute
  '/finance/': typeof FinanceIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/finance/expense': typeof FinanceExpenseLazyRoute
  '/finance': typeof FinanceIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/finance': typeof FinanceRouteWithChildren
  '/finance/expense': typeof FinanceExpenseLazyRoute
  '/finance/': typeof FinanceIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/finance' | '/finance/expense' | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/finance/expense' | '/finance'
  id: '__root__' | '/' | '/finance' | '/finance/expense' | '/finance/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FinanceRoute: typeof FinanceRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FinanceRoute: FinanceRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/finance"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/finance": {
      "filePath": "finance.tsx",
      "children": [
        "/finance/expense",
        "/finance/"
      ]
    },
    "/finance/expense": {
      "filePath": "finance.expense.lazy.tsx",
      "parent": "/finance"
    },
    "/finance/": {
      "filePath": "finance.index.lazy.tsx",
      "parent": "/finance"
    }
  }
}
ROUTE_MANIFEST_END */
