/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FinanceLayoutImport } from './routes/finance/index.lazy'

// Create Virtual Routes

const FinanceImport = createFileRoute('/finance')()
const IndexLazyImport = createFileRoute('/')()
const FinanceExpensesLazyImport = createFileRoute('/finance/expenses')()

// Create/Update Routes

const FinanceRoute = FinanceImport.update({
  path: '/finance',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)../routes/finance/_layout/index.lazy').then((d) => d.Route))

const FinanceExpensesLazyRoute = FinanceExpensesLazyImport.update({
  path: '/expenses',
  getParentRoute: () => FinanceRoute,
} as any).lazy(() =>
  import('./routes/finance/expenses.lazy').then((d) => d.Route),
)

const FinanceLayoutRoute = FinanceLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => FinanceRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceImport
      parentRoute: typeof rootRoute
    }
    '/finance/_layout': {
      id: '/finance/_layout'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceLayoutImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesLazyImport
      parentRoute: typeof FinanceImport
    }
  }
}

// Create and export the route tree

interface FinanceRouteChildren {
  FinanceLayoutRoute: typeof FinanceLayoutRoute
  FinanceExpensesLazyRoute: typeof FinanceExpensesLazyRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceLayoutRoute: FinanceLayoutRoute,
  FinanceExpensesLazyRoute: FinanceExpensesLazyRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/finance': typeof FinanceLayoutRoute
  '/finance/expenses': typeof FinanceExpensesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/finance': typeof FinanceLayoutRoute
  '/finance/expenses': typeof FinanceExpensesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/finance': typeof FinanceRouteWithChildren
  '/finance/_layout': typeof FinanceLayoutRoute
  '/finance/expenses': typeof FinanceExpensesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/finance' | '/finance/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/finance' | '/finance/expenses'
  id: '__root__' | '/' | '/finance' | '/finance/_layout' | '/finance/expenses'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FinanceRoute: typeof FinanceRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FinanceRoute: FinanceRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/finance"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/finance": {
      "filePath": "finance",
      "children": [
        "/finance/_layout",
        "/finance/expenses"
      ]
    },
    "/finance/_layout": {
      "filePath": "finance/_layout.tsx",
      "parent": "/finance"
    },
    "/finance/expenses": {
      "filePath": "finance/expenses.lazy.tsx",
      "parent": "/finance"
    }
  }
}
ROUTE_MANIFEST_END */
